# Site Info
title: Frics's blog
tagline: 'for Programming study'
description: 'blog Programming study'
url: http://frics.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Frics
  description: 프로그래밍 공부 노트
  gravatar: 0a638fc7996869b1b67fb90ccf77dcfe # md5 hash of your email address
  contact:
    #linkedin:
    github:    https://github.com/frics
    instagram:    https://www.instagram.com/sseungs_23_/
    #facebook:
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:jimmy9711@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://frics.github.io/public/img/picture.JPG
  caption: Original Photo &copy; James Choi. in SokCho, Feb 2019.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: #'UA-93172815-1' # leave blank if you don't want google analytics
#disqus_short_name: 'ratsgo-github-io' # leave blank if you don't want disqus
#디스커스 추가할때 넣자
